### ISSUE TITLE
Requires Ruby 2.1+ (uses keyword arguments)

### ISSUE THREAD

**Issue by seandmccarthy** [CoralineAda/society#1]
Hi. Great gem!

I think it's worth noting in the README that it requires Ruby 2.1(.5+), and also a Rails 4(.1?) app. It caught me out. Thanks!

**Comment by zamith** [comment]
Keyword arguments were introduced in ruby 2.0, which is the oldest version that has not been EOL'ed. It does require ruby 2.1 because it uses required keyword arguments.

Not that it makes a huge difference, just pointing that out.

I do think it is nice for gem to explicitly state the version requirements they need to run.

**Comment by CoralineAda** [comment]
I put something in the Gemfile to throw an exception unless the Ruby version is > 2.0. Hopefully that resolves the issue.

**Comment by zamith** [comment]
@CoralineAda But the Gemfile won't be run on gem install, will it?

**Comment by CoralineAda** [comment]
Hmm, you may be right.

**Comment by seandmccarthy** [comment]
@zamith (MRI) Ruby < 2.0 may be EOL, but it isn't for JRuby. Those using JRuby could benefit from knowing this won't work for them.

**Comment by zamith** [comment]
Sure. I agree this should be noted on the README, as I believe it is now.
